seed = 0
exp_path = "expdir/adult/tvae"
data_path = "data/adult/"
device = "cuda:0"

[train_params]
epochs = 3
lr = 0.00032660626928874973
batch_size = 512  # 4096
loss_factor = 1.1675
compress_dims = [
    256,
    512,
]
decompress_dims = [
    256,
    512,
]

[sample]
num_samples = 21600
batch_size = 256 # 21600
seed = 0

[eval.type]
eval_model = "catboost"      # mlp  catboost
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[dp.common]
max_grad_norm = 0.01
sigma = 2
delta = 1e-05
noise_multiplicity_K = 4
