seed = 0
exp_path = "expdir/king/"
data_path = "data/king/"
num_numerical_features = 17
model_type = "mlp"
device = "cuda:0"

[model_params]
d_in = 30
is_y_cond = false
num_classes = 0

[model_params.rtdl_params]
d_layers = [
    256,
    1024,
    1024,
    1024,
    1024,
    256,
]
dropout = 0.0

[diffusion_params]
num_timesteps = 100
gaussian_loss_type = "mse"

[train.main]
steps = 30000
lr = 0.0007444465590958975
weight_decay = 0.0
batch_size = 4096

[train.T]
seed = 0
normalization = "quantile"  # "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = 'analogbit'
y_policy = "default"

[sample]
num_samples = 27600
batch_size = 10000
seed = 0

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[dp]
phase = 1
S = 0
max_grad_norm = 1
sigma = 1.5
delta = 1e-5
noise_multiplicity_K = 4
