seed = 0
exp_path = "expdir/adult/dm_mlp_best"
data_path = "data/adult/"
model_type = "mlp"
num_numerical_features = 6
device = "cuda:0"

[model_params]
d_in = 34
is_y_cond = true
num_classes = 2

[model_params.rtdl_params]
d_layers = [
    512,
    1024,
    1024,
    512,
]
dropout = 0.0

[diffusion_params]
num_timesteps = 100
gaussian_loss_type = "mse"
scheduler = "cosine"

[train.main]
steps = 5200
lr = 0.0010288294884237426
weight_decay = 0.0
batch_size = 512

[train.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "analogbit"
y_policy = "default"

[sample]
num_samples = 52096
batch_size = 256
seed = 4

[eval.type]
eval_model = "mlp"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[dp.common]
enabled_stages = [
    "0"
]
max_grad_norm = 0.7
sigma = 1.5
delta = 1e-05
noise_multiplicity_K = 1

[dp.0]
steps = 5200
S = 0
T = 100

[dp.1]
S = 0
T = 100

[dp.2]
S = 0
T = 0

[dp.3]
S = 0
T = 0
