seed = 0
exp_path = "expdir/adult/dm_catboost_eps"
data_path = "data/adult/"
model_type = "mlp"
num_numerical_features = 6
device = "cuda:0"

[model_params]
d_in = 34
is_y_cond = true
num_classes = 2

[model_params.rtdl_params]
d_layers = [
    1024,
    256,
]
dropout = 0.0

[diffusion_params]
num_timesteps = 100
gaussian_loss_type = "mse"
scheduler = "cosine"

[train.main]
steps = 5200
lr = 0.0015187055496633354
weight_decay = 0.0
batch_size = 512

[train.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "analogbit"
y_policy = "default"

[sample]
num_samples = 26048
batch_size = 256
seed = 4

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[dp.common]
enabled_stages = [
    "0",
    "1",
    "2"
]
max_grad_norm = 0.01
sigma = 2
delta = 1e-05
noise_multiplicity_K = 4

[dp.0]
steps = 100
S = 94
T = 100

[dp.1]
max_grad_norm = 1.5
sigma = 2.5
steps = 100
S = 66
T = 94

[dp.2]
max_grad_norm = 0.05
sigma = 4
steps = 5000
S = 0
T = 66
